name: Push issue to Discord

on:
  issues:
    types: [ opened ]

jobs:
  issue-to-discord:
    name: Push issue to Discord
    runs-on: ubuntu-latest
    steps:
      - name: Push issue to Discord
        env:
          DISCORD_URL: ${{ secrets.BOT_TESTBED_URL }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"$ISSUE_TITLE (#$ISSUE_NUMBER)\\n$ISSUE_URL\"}" $DISCORD_URL
